// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQlTD6zBHUBr2_aUHf4yoWkMAubsjxbak',
    appId: '1:667577209576:web:c09b88e6b15a013c0fef5d',
    messagingSenderId: '667577209576',
    projectId: 'smart-ai-alarm-2f71d',
    authDomain: 'smart-ai-alarm-2f71d.firebaseapp.com',
    databaseURL: 'https://smart-ai-alarm-2f71d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-ai-alarm-2f71d.firebasestorage.app',
    measurementId: 'G-BZ9ZBNPWYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQlTD6zBHUBr2_aUHf4yoWkMAubsjxbak',
    appId: '1:667577209576:android:361c532c68988bf90fef5d',
    messagingSenderId: '667577209576',
    projectId: 'smart-ai-alarm-2f71d',
    databaseURL: 'https://smart-ai-alarm-2f71d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-ai-alarm-2f71d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQlTD6zBHUBr2_aUHf4yoWkMAubsjxbak',
    appId: '1:667577209576:ios:REPLACE_WITH_YOUR_IOS_APP_ID',
    messagingSenderId: '667577209576',
    projectId: 'smart-ai-alarm-2f71d',
    databaseURL: 'https://smart-ai-alarm-2f71d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-ai-alarm-2f71d.firebasestorage.app',
    iosBundleId: 'com.smartalarm',
  );
}
